apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp
    type: frontend
spec:
  replicas: 6
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            name: POSTGRES_PASSWORD
            value: mysecretpassword
  selector:
    withLabels:
       app: myapp
       type: frontend

