apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp-rc
    labels:
        app: myapp
        type: frontend
spec:
  - template:
        metadata:
            name: myapp-rc
            labels:
                app: myapp
                type: frontend
        spec:
            containers:
                - name: postgres
                  image: postgres
                  env:
                    - name: POSTGRES_PASSWORD
                      value: mysecretpassword
    replicas: 3
