apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
spec:
  replicas: 3
  template:
    metadata:
      name: redis-slave-pod
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
        - name: redis-slave
          image: redis-slave
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
  selector:
    withLabels:
      app: redis
      role: master
      tier: backend