apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 6
  template: 
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: postgres-container
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
  selector:
    withLabels:
        app: myapp
        tier: frontend

