apiVersion: v1
kind: Service
metadata:
    name: myapp-service
    labels:
        app: myapp
        tier: frontend
spec:
    type: ClusterIP
    ports:
      - port: 80
        nodePort: 31000
        targetPort: 8080
    selector:
        app: myapp
        tier: frontend
        