apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
    app: myapp
    tier: frontend