apiVersion: v1
kind: Service
metadata:
  name: image-processing
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    tier: backend

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
     app: myapp
     tier: frontend